### ISSUE TITLE
Possible to add support for native clickhouse protocol

### ISSUE THREAD

**Issue by langchain-infra** [maximdanilchenko/aiochclient#111]
Does aiochclient support the native clickhouse protocol? unable to get it working over port 9000.

**Comment by maximdanilchenko** [comment]
Hi @langchain-infra! Unfortunately no. This is http only client.
May be in the future we will add native protocol support, but not now.

As for now if you need async native protocol you can use alternatives such as [asynch](https://github.com/long2ice/asynch) or async wrapper of [clickhouse-driver](https://github.com/mymarilyn/clickhouse-driver) - [aioch](https://github.com/mymarilyn/aioch)

**Comment by langchain-infra** [comment]
Got it no problem thanks!
