### ISSUE TITLE
Problem with parsing single quotes in arrays

### ISSUE THREAD

**Issue by samnoyes** [maximdanilchenko/aiochclient#112]
Hi, I noticed an issue with the client when single quotes are included in elements within arrays. Basically, when I inspect my clickhouse db directly, I see that my "tags" array looks like this:

['another\'_qa','boot\'_qa']

By using length() I confirm that these are two distinct items. However, when I run ch.fetch("select tags from...") they are returned as a single tag!

The following:

    test = await ch.fetch("select tags from runs where id='<run id>'")
    test_result = dict(test[0])
    print(test_result, len(test_result['tags']))

prints this:

    {'tags': ["another'_qa','boot'_qa"]} 1

I assume this must be an issue with `seq_parser`.

**Comment by samnoyes** [comment]
seems to be fixed in a later version

**Comment by Maksim-Burtsev** [comment]
I think this issue was fixed in one of the previous PR's. 

@maximdanilchenko can you make new release?
