### ISSUE TITLE
does not support connect through chproxy

### ISSUE THREAD

**Issue by luckykris** [maximdanilchenko/aiochclient#15]
my ch cluster is expose by chproxy , aiochclient can not connect.

**Comment by maximdanilchenko** [comment]
@luckykris, hi! aiochclient uses aiohttp library as a transport. So may be aiohttp docs may help: https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support

**Comment by luckykris** [comment]
> @luckykris, hi! aiochclient uses aiohttp library as a transport. So may be aiohttp docs may help: https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support

my chproxy is configured BasicAuth , so i configure ClientSession with BasicAuth , and it works, but "client.is_alive() " still raise assertException . here is the code:
```
async def query_clickhouse(sql):
    async with ClientSession(auth=BasicAuth(ck_user,ck_password,'utf-8')) as s:
        client = ChClient(s, url="http://%s:%s" % (ck_host, ck_port), user=ck_user, password=ck_password)
        assert await client.is_alive()
```
i think it`s because chproxy only support BasicAuth but aioclient pass auth info as http parameters .

**Comment by luckykris** [comment]
so if use chproxy , is_alive() method won't work,  the http response body is "Code: 62, e.displayText() = DB::Exception: Empty query (version 19.13.1.11)"
so is_alive() method alway return False

**Comment by maximdanilchenko** [comment]
> i think it`s because chproxy only support BasicAuth but aioclient pass auth info as http parameters .
You can leave user and password params empty to not use them, like:
```
client = ChClient(s, url="http://%s:%s" % (ck_host, ck_port))
```

**Comment by maximdanilchenko** [comment]
> is_alive() method alway return False
Does queries of other types work?
