### ISSUE TITLE
Problem with request answer parsing

### ISSUE THREAD

**Issue by Tornhard** [maximdanilchenko/aiochclient#16]
Hello! 
I have a problem with your driver in request answer parsing. When I request array of arrays of ints from the database, i get ints misplaced in sub arrays.

This is create table code:
CREATE TABLE IF NOT EXISTS user_logs
 (
created_at Int64, user_id Int32, event_id Int32, entity String, intention String, result Array(Array(Int32))
) ENGINE = MergeTree 
PARTITION BY (toYYYYMM(toDate(intDiv(created_at, 1000)))) 
ORDER BY (created_at)

Insert data code:
INSERT INTO user_logs (created_at, user_id, event_id, entity, intention, result) values 
        [[1579524424420, 3562, 4, 'camera_contract_binding_to_stage', '{}', [[1, 1], [2, 2]]]]

Request:
sql = """SELECT created_at, user_id, event_id, entity, intention, result 
FROM user_logs 
WHERE hasAny(result, [[toInt32(1), toInt32(1)]])"""

Executing request:
rows: List[aiochclient.records.Record] = await client.fetch(sql)
print([list(row.values()) for row in rows])

Here is what I expect: 
[['1579256044578', '3562', '4', 'camera_contract_binding_to_stage', '{}', '[[1, 1], [2, 2]]']]

Here is what I get:
[['1579256044578', '3562', '4', 'camera_contract_binding_to_stage', '{}', '[[1], [1], [2], [2]]']]

I`ve checked this behavior with 1.2.1 and 1.3.0rc0

**Comment by maximdanilchenko** [comment]
Hello! Thank you for the issue!

I found that it's because of `.strip("[]")` [here](https://github.com/maximdanilchenko/aiochclient/blob/master/aiochclient/types.py#L223):

```python
>>> '[[1,2,3],[4,5,6]]'.strip('[]')
'1,2,3],[4,5,6'
```

I will fix it soon.
