### ISSUE TITLE
CH Types missing: IPv4, IPv6

### ISSUE THREAD

**Issue by elrik75** [maximdanilchenko/aiochclient#17]
CH documentation for IPv4: https://clickhouse.yandex/docs/en/data_types/domains/ipv4/

Here the error when CH send an IPv4:

`aiochclient.exceptions.ChClientError: Unrecognized type name: 'IPv4'`

IPs should be converted in object from `ipaddress` module: https://docs.python.org/3/library/ipaddress.html

**Comment by maximdanilchenko** [comment]
https://pypi.org/project/aiochclient/1.3.1/
