### ISSUE TITLE
UUID type support

### ISSUE THREAD

**Issue by ormwish** [maximdanilchenko/aiochclient#3]
Hi!

Pls add transparent UUID type support to your client (Python UUID to ClickHouse UUID type)

**Comment by maximdanilchenko** [comment]
@ormwish, I will try to implement it this year.

**Comment by ormwish** [comment]
@maximdanilchenko that would be great! I'll try to use string notation with this data-type for now and post a comment if this kind of workaround works.

**Comment by maximdanilchenko** [comment]
Uploaded on pypi: https://pypi.org/project/aiochclient/0.1.1/
