### ISSUE TITLE
Branch for backports to 1.X

### ISSUE THREAD

**Issue by aamalev** [maximdanilchenko/aiochclient#42]
Please create a branch and I'll add a backport patch #41

**Comment by maximdanilchenko** [comment]
@aamalev I'm sorry, I didn't get it. Why do we need a backport patch? What thing exactly will be not compatible with previous versions?

**Comment by maximdanilchenko** [comment]
Anyway, I created it: https://github.com/maximdanilchenko/aiochclient/tree/1.x :)

**Comment by aamalev** [comment]
@maximdanilchenko I meant a branch 1.x from the tag v1.4.0 (:

**Comment by maximdanilchenko** [comment]
Oh, sorry - branch name is 1.4.x
