### ISSUE TITLE
Record Converter Exception for Invalid UTF-8 Bytestrings

### ISSUE THREAD

**Issue by nmr-cf** [maximdanilchenko/aiochclient#51]
Hi,

in the scenario where the byte-string content being queried from Clickhouse contains invalid bytes (they cannot be decoded to utf-8), the `aiochclient `will throw an exception.  The relevant code is here: https://github.com/maximdanilchenko/aiochclient/blob/master/aiochclient/records.py#L74

So for example, let's suppose we pull some data that looks like this:

```
Column A  (UInt32Type) | Column B (StrType)
----------------------------------------------
             1         |  b'Hello\xf1aWorldTest'
```

Then the corresponding tuple expansion in `decode` will look like:

```
( (<function UInt32Type.convert>, b'1'),
(<function StrType.convert>, b'Hello\xf1aWorldTest'))
```
Which will throw an exception akin to `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 5: invalid continuation byte`.

Now - while it is not generally advisable to store invalid bytestring content in one's database, there are scenarios where this might be required. In these scenarios it would be preferable if `aiochclient` could simply return the raw bytestring data instead of throwing an exception.  Thank you!

**Comment by maximdanilchenko** [comment]
@nmr-cf, hi! Thank you for the issue. I added decode flag to all fetch queries to return bytes. You can see it in 85e37fc71f13b0eaae2d2c752280dba71c46d54d commit. Will be available in next release.
