### ISSUE TITLE
Clickhouse 'Map' type not supported in inserts via ChClient.execute()

### ISSUE THREAD

**Issue by tomslot** [maximdanilchenko/aiochclient#54]
CREATE TABLE map_test(
    map_field Map(String, String)
)
----------
client.execute("INSERT INTO map_test VALUES", {'hello': 'world'})

Gives:
aiochclient.exceptions.ChClientError: Unrecognized type: '<class 'dict'>'. The value type should be exactly one of int, float, str, dt.date, dt.datetime, tuple, list, uuid.UUID (or None). No subclasses yet.

Shame :(

**Comment by crmaxx** [comment]
fixed in https://github.com/maximdanilchenko/aiochclient/pull/77
