### ISSUE TITLE
LowCardinality type support

### ISSUE THREAD

**Issue by BooBSD** [maximdanilchenko/aiochclient#7]
I got `aiochclient.exceptions.ChClientError: Unrecognized type name: 'LowCardinality(String)'`

Could you please add LowCardinality type support?

Is it possible?

Thank you.

**Comment by maximdanilchenko** [comment]
@BooBSD, yes, it is possible. Will implement it as soon as I will have time for it.

**Comment by maximdanilchenko** [comment]
@BooBSD published on pypi version `0.2.2`: https://pypi.org/project/aiochclient/0.2.2
