### ISSUE TITLE
Request to add UInt256 and Int256 types

### ISSUE THREAD

**Issue by lainiwa** [maximdanilchenko/aiochclient#96]
Otherwise they are not getting parsed:
```
Traceback (most recent call last): 
...
aiochclient.exceptions.ChClientError: Unrecognized type name: 'UInt256'
```

**Comment by fmosterts** [comment]
Same for UInt128.

Currently getting this error: `aiochclient.exceptions.ChClientError: Unrecognized type name: 'UInt128'`

Thanks
